Mimetis/Dotmim.Sync

Projects/Dotmim.Sync.Core/Dotmim.Sync.Core.csproj
Projects/Dotmim.Sync.SqlServer/Dotmim.Sync.SqlServer.csproj
Samples/Dotmim.Sync.SampleConsole/Dotmim.Sync.SampleConsole.csproj
Samples/Dotmim.Sync.SampleWebserver/Dotmim.Sync.SampleWebserver.csproj
Tests/Dotmim.Sync.Core.Test/Dotmim.Sync.Core.Test.csproj

also remove some unused references

migrate to netstandard 2.0 final

---

Projects/Dotmim.Sync.Core/Builders/DbBuilder.cs
Projects/Dotmim.Sync.Core/CoreProvider.Database.cs
Projects/Dotmim.Sync.Core/Filter/FilterClause.cs
Projects/Dotmim.Sync.Core/Serialization/DmBinaryConverter/Converters/ObjectConverter.cs
Projects/Dotmim.Sync.Core/SyncConfiguration.cs
Projects/Dotmim.Sync.Core/SyncExtensions.cs
Projects/Dotmim.Sync.MySql/Builders/MySqlObjectNames.cs
Projects/Dotmim.Sync.SqlServer/Builders/SqlBuilderProcedure.cs
Projects/Dotmim.Sync.SqlServer/Builders/SqlObjectNames.cs
Projects/Dotmim.Sync.SqlServer/SqlSyncAdapter.cs
Projects/Dotmim.Sync.Sqlite/Builders/SQLiteObjectNames.cs
Tests/Dotmim.Sync.Tests/AssemblyInfo.cs
Tests/Dotmim.Sync.Tests/MySql/MySqlSyncTests.cs
Tests/Dotmim.Sync.Tests/SyncFilterMultipleFiltersTests.cs
Tests/Dotmim.Sync.Tests/SyncFilterWithVirtualFiltersTests.cs
Tests/Dotmim.Sync.WebApi2.Tests/SqlUtils/HelperDB.cs

Adds the notion of virtual filters.
Fixes issue #81

81 virtual filters

---

Projects/Dotmim.Sync.Core/Filter/SyncParameter.cs

Fixing issue #73

---

Projects/Dotmim.Sync.Core/CoreProvider.Schema.cs
Projects/Dotmim.Sync.Core/Manager/IDbManagerTable.cs
Projects/Dotmim.Sync.MySql/Manager/MySqlManagerTable.cs
Projects/Dotmim.Sync.SqlServer/Manager/SqlManagerTable.cs

Replace List<?> with IEnumerable<?> in IDbManagerTable

---

Projects/Dotmim.Sync.Core/CoreProvider.Database.cs
Projects/Dotmim.Sync.Core/CoreProvider.Schema.cs
Projects/Dotmim.Sync.Core/EnumerableExtensions.cs
Projects/Dotmim.Sync.Core/Manager/DbRelationDefinition.cs
Projects/Dotmim.Sync.MySql/Builders/MySqlBuilderTable.cs
Projects/Dotmim.Sync.MySql/Manager/MySqlManager.cs
Projects/Dotmim.Sync.MySql/Manager/MySqlManagerTable.cs
Projects/Dotmim.Sync.MySql/MySqlManagementUtils.cs
Projects/Dotmim.Sync.SqlServer/Builders/SqlBuilderTable.cs
Projects/Dotmim.Sync.SqlServer/Manager/SqlManager.cs
Projects/Dotmim.Sync.SqlServer/Manager/SqlManagerTable.cs
Projects/Dotmim.Sync.SqlServer/SqlManagementUtils.cs
Projects/Dotmim.Sync.Sqlite/Builders/SQLiteBuilder.cs
Projects/Dotmim.Sync.Sqlite/Builders/SQLiteBuilderTable.cs
Tests/Dotmim.Sync.Tests/BasicTests.cs
Tests/Dotmim.Sync.Tests/Models/AdventureWorksContext.cs
Tests/Dotmim.Sync.Tests/Models/PriceList.cs
Tests/Dotmim.Sync.Tests/Models/PriceListCategory.cs
Tests/Dotmim.Sync.Tests/Models/PriceListDetail.cs
Tests/Dotmim.Sync.Tests/MySql/MySqlBasicTests.cs
Tests/Dotmim.Sync.Tests/Setup.cs
Tests/Dotmim.Sync.Tests/SqlServer/SqlServerBasicTests.cs
Tests/Dotmim.Sync.Tests/StandAlone/DmRelationTests.cs

- Add support composite foreign key
- Raname tests namespace
- fixed issue o f *BuilderTable.BuildForeignKeyConstraintsCommand
- Add test for composite foreign key

Add composite foreign-keys support 

---

LICENSE

Ref issue https://github.com/Mimetis/Dotmim.Sync/issues/131

Adding LICENSE file with MIT License

---

Projects/Dotmim.Sync.Core/Builders/DbBuilder.cs

**Care**: This is the first PR I ever made. So please double check if it's fine.
I only added some keywords to the exceptions thrown when creating a table, so if an exception is thrown, people can comprehend which step went wrong.
Hint: I used the wrong credentials when I committed. So this PR is not tagged to this account.

Added action information for table creation exceptions

---

Readme.md

rename SQLiteSyncProvider to SqliteSyncProvider

fix the sample code

---

Projects/Dotmim.Sync.Core/Dm/DmTable.cs
Projects/Dotmim.Sync.MySql/Builders/MySqlScopeInfoBuilder.cs
Projects/Dotmim.Sync.SqlServer/Builders/SqlScopeInfoBuilder.cs
Projects/Dotmim.Sync.Sqlite/Builders/SqliteScopeBuilder.cs
Projects/Dotmim.Sync.Sqlite/Builders/SqliteScopeInfoBuilder.cs

Fix NRE. Verify reader has rows

---

Projects/Dotmim.Sync.Core/CoreProvider.ApplyChanges.cs

Issue #158 depends on bad table ordering and the fact that sqlite does not support disabling Constraints.
This PR solves the problem by sorting the tables based on the relationships between them regardless of whether the provider supports or not the disabling of constraints.

Fix Issue #158: SQLite Error 19: 'FOREIGN KEY constraint failed'

---

Projects/Dotmim.Sync.Core/Dotmim.Sync.Core.csproj
Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.cs
Projects/Dotmim.Sync.MySql/Dotmim.Sync.MySql.csproj
Projects/Dotmim.Sync.SqlServer.ChangeTracking/Dotmim.Sync.SqlServer.ChangeTracking.csproj
Projects/Dotmim.Sync.SqlServer/Dotmim.Sync.SqlServer.csproj
Projects/Dotmim.Sync.Sqlite/Builders/SQLiteObjectNames.cs
Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj
Projects/Dotmim.Sync.Sqlite/SQLiteManagementUtils.cs
Projects/Dotmim.Sync.Web.Client/Dotmim.Sync.Web.Client.csproj
Projects/Dotmim.Sync.Web.Server/Dotmim.Sync.Web.Server.csproj
Samples/Dotmim.Sync.SampleConsole/Program.cs

Resolving issues #314 and #310 
Labelling  version 0.5.7

Sqlite performance

---

Projects/Dotmim.Sync.Core/SyncTypeConverter.cs

A simple fix for issues when working with `Guid`'s on `Xamarin.iOS`

Fix for Xamarin.iOS Guid parsing

---

Projects/Dotmim.Sync.Sqlite/Builders/SQLiteObjectNames.cs

Fixes issue #458 
All test green

#458 - sqliteprovider only sends local changes

---

Projects/Dotmim.Sync.Core/SyncException.cs

Changed "HttpHeaderMissingExceptiopn" to "HttpHeaderMissingException".

Fixed typo

---

Projects/Dotmim.Sync.SqlServer.ChangeTracking/Builders/SqlChangeTrackingBuilderProcedure.cs
Tests/Dotmim.Sync.Tests/IntegrationTests/SqlServerChangeTracking/SqlServerChangeTrackingTcpTests.cs

fixes the issues I found in https://github.com/Mimetis/Dotmim.Sync/pull/660

Fix the ct stored procedures and add tests that showcases the current behaviour

---

Projects/Dotmim.Sync.MySql/Builders/MySqlBuilderProcedure.cs
Projects/Dotmim.Sync.MySql/Builders/MySqlBuilderTrigger.cs

Sorry I was busy and I wanted to test also on MySql.
This patch fix the issue #674.

Fix for MariaDB 10.3

---

Projects/Dotmim.Sync.Web.Client/HttpRequestHandler.cs

Added missing dotmim-sync-scope-id in HttpRequestHandler.cs

Added missing header, dotmim-sync-scope-id

---

Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.ApplyChanges.cs
Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.Constraints.cs
Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.GetChanges.cs
Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.Metadatas.cs
Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.ScopesTables.cs
Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.StoredProcedures.cs
Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.Table.cs
Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.Timestamp.cs
Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.TrackingTable.cs
Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.Triggers.cs
Projects/Dotmim.Sync.Core/Orchestrators/LocalOrchestrator.Scopes.cs
Projects/Dotmim.Sync.Core/Orchestrators/LocalOrchestrator.Untracked.cs
Projects/Dotmim.Sync.Core/Orchestrators/LocalOrchestrator.Upgrade.cs
Projects/Dotmim.Sync.Core/Orchestrators/RemoteOrchestrator.ServerHistoryScopes.cs
Projects/Dotmim.Sync.Core/Orchestrators/RemoteOrchestrator.ServerScopes.cs
Projects/Dotmim.Sync.Core/Orchestrators/RemoteOrchestrator.Upgrade.cs
Projects/Dotmim.Sync.Core/Setup/SyncSetup.cs
Projects/Dotmim.Sync.Core/SyncOptions.cs

Sql command timeout parametrized from SyncSetup for execute sql commands with a lot of data

Sql command timeout

---

Dotmim.Sync.sln.DotSettings
Projects/Dotmim.Sync.Core/Setup/SyncSetup.cs
Projects/Dotmim.Sync.SqlServer.ChangeTracking/Builders/SqlChangeTrackingBuilderProcedure.cs
Projects/Dotmim.Sync.SqlServer/Builders/SqlBuilderProcedure.cs

Reverts Mimetis/Dotmim.Sync#923 as tests are failing

Revert "Fixes issues with tables that contain non-comparable columns"

---

Projects/Dotmim.Sync.Core/Dotmim.Sync.Core.csproj
Projects/Dotmim.Sync.MariaDB/Dotmim.Sync.MariaDB.csproj
Projects/Dotmim.Sync.MySql/Dotmim.Sync.MySql.csproj
Projects/Dotmim.Sync.PostgreSql/Dotmim.Sync.PostgreSql.csproj
Projects/Dotmim.Sync.SqlServer.ChangeTracking/Dotmim.Sync.SqlServer.ChangeTracking.csproj
Projects/Dotmim.Sync.SqlServer/Dotmim.Sync.SqlServer.csproj
Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj
Projects/Dotmim.Sync.Web.Client/Dotmim.Sync.Web.Client.csproj
Projects/Dotmim.Sync.Web.Server/Dotmim.Sync.Web.Server.csproj
Samples/Dotmim.Sync.SampleConsole/Dotmim.Sync.SampleConsole.csproj

This should enable newer features without changing anything about the compilation targets

Update to C# LangVersion 11.0

---

Projects/Dotmim.Sync.Core/Serialization/LocalJsonSerializer.cs

This was a fairly complicated class, and it should be easier to read now. The commits should be self-explanatory, when read one by one.

Simplify LocalJsonSerializer

---

Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.cs

feat: Avoid throwing NRE when creating snapshot with SyncParameters with null value

---

Readme.md

This is more concise and conventional. And automatically shows the latest stable version.

Use NuGet badge on Readme

---

Dotmim.Sync.sln

This is a convenience that allows easily modifying root-level files inside of Visual Studio

show root-level files in solution

---

Projects/Dotmim.Sync.Web.Client/Args/HttpContextArgs.cs
Projects/Dotmim.Sync.Web.Client/Orchestrators/WebRemoteOrchestrator.cs
Tests/Dotmim.Sync.Tests/Core/KestrellTestServer.cs
Tests/Dotmim.Sync.Tests/HttpTests/HttpTests.cs

This pull request introduces several enhancements to improve error handling and customization in the application.
- Added `HttpResponseFailureArgs` class to encapsulate details of failed HTTP responses, including status code, reason phrase, error content, headers, and request URI.
- Implemented `OnHttpResponseFailure` extension method for `WebRemoteOrchestrator` class to register actions for handling failed HTTP responses.
- Added `InvokeResponseFailureInterceptors` method to `WebRemoteOrchestrator` class to trigger interception logic for processing failed HTTP responses.
- Introduced `IsAuthorisationEnabled` property to `Kestrell` class to control authorization mechanism simulation.
- Addition of the `OnHttpResponseFailure_RegisterAction_ActionIsInvokedOnHttpResponseFailureAsync` method …

Enhancement: Addition of Client Interceptor for Handling HTTP Error Responses

---

Projects/Dotmim.Sync.Core/Batch/BatchInfo.cs
Projects/Dotmim.Sync.Core/Orchestrators/ApplyChanges/BaseOrchestrator.ApplyChanges.cs
Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.BatchInfo.cs
Projects/Dotmim.Sync.Core/Serialization/DataContractResolver.cs
Projects/Dotmim.Sync.Core/Serialization/LocalJsonSerializer.cs
Projects/Dotmim.Sync.Web.Client/Orchestrators/WebRemoteOrchestrator.cs
Projects/Dotmim.Sync.Web.Server/WebServerAgent.cs
Tests/Dotmim.Sync.Tests/TcpTests/TcpConflictsTests.cs
Tests/Dotmim.Sync.Tests/UnitTests/BatchInfos/BatchInfosTests.cs
Tests/Dotmim.Sync.Tests/UnitTests/Orchestrators/LocalOrchestrator.GetChanges.Tests.cs
Tests/Dotmim.Sync.Tests/UnitTests/Orchestrators/RemoteOrchestrator.GetChanges.Tests.cs

Found via InferSharp
Ready to merge. The only test failure is fixed in another PR

Correctly dispose resources

---

Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj
Tests/Dotmim.Sync.Tests/HttpTests/HttpTests.cs
Tests/Dotmim.Sync.Tests/Misc/HelperDatabase.cs
Tests/Dotmim.Sync.Tests/Models/AdventureWorksExtensions.cs
Tests/Dotmim.Sync.Tests/TcpTests/TcpTests.ScenarioTests.cs
Tests/Dotmim.Sync.Tests/UnitTests/Interceptors/Interceptors.StoredProcedures.Tests.cs
Tests/Dotmim.Sync.Tests/UnitTests/Interceptors/Interceptors.Tables.Tests.cs
Tests/Dotmim.Sync.Tests/UnitTests/Interceptors/Interceptors.TrackingTables.Tests.cs
Tests/Dotmim.Sync.Tests/UnitTests/Interceptors/Interceptors.Triggers.Tests.cs
Tests/Dotmim.Sync.Tests/UnitTests/Orchestrators/RemoteOrchestrator.Tests.cs
Tests/Dotmim.Sync.Tests/UnitTests/Orchestrators/RemoteOrchestrator.Triggers.Tests.cs
Tests/Dotmim.Sync.Tests/packages.lock.json

This is in hopes of making the tests run faster, and should add features.
I also used `await using` on all `IAsyncDisposable` objects in the _Tests_ project with the same goal.
The only test failure should be the one I fixed in another PR.

update xUnit packages and use IAsyncDisposable

---

pipelines/azure-pipelines-sql.yml
pipelines/azure-pipelines-template.yml

If this works, there should be an error reported on this PR, until the tests are all green on master branch

Fix test failure reporting from Azure to GitHub

---

Projects/Dotmim.Sync.Core/Orchestrators/DbConnectionRunner.cs

Conditional compilation, for the win.

use async disposal, if possible

---

Projects/Dotmim.Sync.Core/Serialization/LocalJsonSerializer.cs

This solves one leak found by InferSharp

Improve serializer disposal

---

Projects/Dotmim.Sync.Core/Dotmim.Sync.Core.csproj
Projects/Dotmim.Sync.MariaDB/Dotmim.Sync.MariaDB.csproj
Projects/Dotmim.Sync.MySql/Dotmim.Sync.MySql.csproj
Projects/Dotmim.Sync.PostgreSql/Dotmim.Sync.PostgreSql.csproj
Projects/Dotmim.Sync.SqlServer.ChangeTracking/Dotmim.Sync.SqlServer.ChangeTracking.csproj
Projects/Dotmim.Sync.SqlServer/Dotmim.Sync.SqlServer.csproj
Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj
Projects/Dotmim.Sync.Web.Client/Dotmim.Sync.Web.Client.csproj
Projects/Dotmim.Sync.Web.Server/Dotmim.Sync.Web.Server.csproj
Samples/Dotmim.Sync.SampleConsole/Dotmim.Sync.SampleConsole.csproj
Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj

Will give access to features like collection expressions and primary constructors

bump language version

---

Projects/Dotmim.Sync.Sqlite/Builders/SQLiteObjectNames.cs
Projects/Dotmim.Sync.Sqlite/Builders/SqliteTableBuilder.cs
Projects/Dotmim.Sync.Sqlite/SQLiteSyncAdapter.cs
Projects/Dotmim.Sync.Sqlite/SqliteSyncProvider.cs
Samples/Dotmim.Sync.SampleConsole/SqliteSyncDownloadOnlyProvider.cs
Tests/Dotmim.Sync.Tests/Setup.cs
Tests/Dotmim.Sync.Tests/TcpTests/TcpTests.ScenarioTests.cs

Abderrahmane ahmam master

---

Projects/Dotmim.Sync.Core/Orchestrators/ApplyChanges/BaseOrchestrator.ApplyChanges.cs
Projects/Dotmim.Sync.Core/Orchestrators/ApplyChanges/BaseOrchestrator.ApplyRow.cs
Projects/Dotmim.Sync.Core/Orchestrators/ApplyChanges/RemoteOrchestrator.ApplyChanges.cs
Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.Constraints.cs
Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.cs

This ensures that DbCommand objects are more reliably disposed when needed.

prevent leaks

---

Projects/Dotmim.Sync.Core/Orchestrators/ApplyChanges/BaseOrchestrator.ApplyChanges.cs

A continuation of the simplification in https://github.com/Mimetis/Dotmim.Sync/pull/1242

use pattern matching

---

Projects/Dotmim.Sync.Core/Orchestrators/ApplyChanges/BaseOrchestrator.ApplyChanges.cs

No severities were changed.
see also: https://stackoverflow.com/questions/52200484/why-logging-doesnt-use-string-interpolation

use structured logging, not interpolation

---

Projects/Dotmim.Sync.Core/Orchestrators/ApplyChanges/BaseOrchestrator.ApplyChanges.cs
Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.cs

The most complex method in the project is the `InternalApplyTableChangesAsync` method.
Anything that can be done to simplify it would be useful.

Simplify orchestrator code
