Mimetis/Dotmim.Sync

Readme.md, Tests/Dotmim.Sync.Tests/MySql/MySqlAllColumnsTests.cs, Tests/Dotmim.Sync.Tests/SqlUtils/HelperDB.cs, Tests/Dotmim.Sync.Tests/SyncProvAndDeprovTests.cs, appveyor.yml, installMySql.ps1, uninstallMySql.ps1
Hi!
1) I fixed the automated tests on my dev machine 
2) used the appveyor.yml of #78 as foundation (big thanks to @ashalkhakov)
but had to change it a bit to get the tests to work
All tests now are green on appveyor except of two:
1) Dotmim.Sync.Test.MySql.MySqlAllColumnsTests.OneRowFromServer
...fails due to the DATETIME vs DATETIME(6) issue with MySql version 5.7 (which is the only one available on appveyor)
Please refer to this issue: #77
2) Dotmim.Sync.Tests.SyncConflictsTests.ConflictOnUniqueConstraint 
...also fails on my dev machine. I do not know why, yet. Maybe you can have a look @Mimetis ? :-)
In order to use this CI for Dotmim.Sync:
1) Login to appveyor using your github account
2) [add the Dotmim.Sync project](https://1drv.ms/u/s!AhVbOiFFuzx_11vAFiYnRdNjervV)
3) [configure …
=> CI for unit- and integration tests

Projects/Dotmim.Sync.Core/Serialization/DmBinaryConverter/Converters/ObjectConverter.cs, Projects/Dotmim.Sync.MySql/Builders/MySqlObjectNames.cs, Projects/Dotmim.Sync.SqlServer/Builders/SqlObjectNames.cs, Projects/Dotmim.Sync.SqlServer/SqlSyncAdapter.cs, Projects/Dotmim.Sync.Sqlite/Builders/SQLiteObjectNames.cs, Tests/Dotmim.Sync.Tests/AssemblyInfo.cs, Tests/Dotmim.Sync.Tests/MySql/MySqlSyncTests.cs, Tests/Dotmim.Sync.WebApi2.Tests/SqlUtils/HelperDB.cs
Added assembly attribute 
[assembly: CollectionBehavior(DisableTestParallelization = true)]
=> tests are now executed sequentially (not parallel) which means they are slower, but they do not fail
Fixed trigger creation by re-adding the standard postfix "_trigger" to SQLite,MSSQL,MySQL.
If no custom prefix was provided the triggers names would clash with those of the stored procedures. This caused nearly all tests to fail.
This fixed issue #83
=> 83 ci fixes

Projects/Dotmim.Sync.Core/Dm/DmTableSurrogate.cs
Setting up trigger pre- and postfixes using a webproxy (asp.net) does not work.
The pre- and postfixes are ignored on the server side (verifyable with SqlServer provider)
Completes issue #51
=> Fix for #51 - when using webproxy, pre/postfixes of triggers are ignored

Projects/Dotmim.Sync.Core/CoreProvider.GetChanges.cs, Projects/Dotmim.Sync.Web.Server/WebProxyServerProvider.cs
Also, do not create BatchDirectory on client, if BatchMode is off.
=> Fix - SyncConfiguration is overriden before BatchDirectory is persisted

Projects/Dotmim.Sync.MySql/Builders/MySqlBuilderTrigger.cs
Hi,
I was just trying out the current filters implementation on MySql and encountered this bug where triggers are not properly generated.
For example:
**Insert trigger before fix:**
**Insert trigger after fix:**
Same thing for update and delete triggers.
=> MySql trigger builder fix

Projects/Dotmim.Sync.MySql/Builders/MySqlDbMetadata.cs
In MySql when column type is "binary", Dotmim.Sync throws an exception.
Turns out this type is not handled properly.
=> Mysql binary fix

Projects/Dotmim.Sync.Sqlite/Manager/SQLiteDbMetadata.cs
Current implmenetation missing one of the basic SQLite data type - `REAL` ([SQLite data type](https://www.sqlite.org/datatype3.html))
Added convertion `SQLite REAL` <-> `C# Double`
=> Added support for "REAL" data type in SQLite

Projects/Dotmim.Sync.Core/SyncResult.cs, Projects/Dotmim.Sync.Web.Client/WebClientOrchestrator.cs, Projects/Dotmim.Sync.Web.Server/WebServerOrchestrator.cs
Fixes in RyncResults that may cause debug errors because NullReferenceException
AfterDeserializedRows was not called while HTTP-sync
Correct sync on server in case there is not body hash in request headers
=> Minor fixes

Projects/Dotmim.Sync.Web.Client/HttpRequestHandler.cs
Some minor fixes for HttpRequestHandler I came across while testing. The first will fix an ObjectDisposedException when the client will retry to send a request again, cause the ByteArrayContent will be disposed on first failed request. Further I removed the call to responseStream.FlushAsync to avoid an InvalidOperationException as the stream is a read-only stream that doesn't need to be flushed.
=> Patch for HttpRequestHandler

Projects/Dotmim.Sync.Core/Setup/SyncSetup.cs, Projects/Dotmim.Sync.SqlServer.ChangeTracking/Builders/SqlChangeTrackingBuilderProcedure.cs, Projects/Dotmim.Sync.SqlServer.ChangeTracking/Builders/SqlChangeTrackingBuilderTrackingTable.cs, Tests/Dotmim.Sync.Tests/IntegrationTests/SqlServerChangeTracking/SqlServerChangeTrackingTcpTests.cs
The behaviour should be that when the sync setup contains columns, only those columns should be involved in the sync.
=> Fix issue in sql change tracking when columns are updated that are not in the setup

Projects/Dotmim.Sync.SqlServer/SqlSyncAdapter.cs
Changing the value of DateTimeOffset when the rowValue < SqlDateMin throws exception when record.SetValue is called because the types are different.  There is no reason to be changing the data on DateTimeOffset since it can handle values lower than SqlDateMin.  Only DateTime & SmallDateTime have limits so I also adjusted the code to handle those.
Closes #680
=> Exception in SqlSyncAdapter.cs. Remove DateTimeOffset conversion and handle SmallDateTime better

Projects/Dotmim.Sync.Core/Args/SessionArgs.cs, Projects/Dotmim.Sync.Core/Orchestrators/LocalOrchestrator.cs, Projects/Dotmim.Sync.Core/SyncAgent.cs, Tests/Dotmim.Sync.Tests/UnitTests/Orchestrators/LocalOrchestrator.Tests.cs
Added SyncResult to the 'SessionEndArgs' because it's not possible to get the SyncResult in relation to the SyncContext like before.  The SyncContext is now being passed around everywhere and doesn't exist as GetContext() on the 'WebRemoteOrchestrator' anymore.  Adding this to the SessionEnd allows users to intercept the event and perform custom operations on the SyncResult in relation to the SyncContext such as a custom session ended event which inserts statistics into a custom tables based on the sync scope id which exists on the context.
=> Update session end to contain SyncResult

Projects/Dotmim.Sync.Core/Orchestrators/LocalOrchestrator.Upgrade.cs
Fixes #784
The `PRAGMA` statement seem to create its own transaction, causing a 'cannot start a transaction within a transaction' error
=> Remove PRAGMA statement from query, causing SQLite error

docs/Configuration.rst
I'm going through your documentation and just noticed an incorrect variable name.  Nothing exciting.
=> Incorrect variable called in SynchronizeAsync

Projects/Dotmim.Sync.MySql/Builders/MySqlBuilderTrigger.cs
- Dotmim.Sync.MariaDB
- Dotmim.Sync.MySql
`INSERT ... ON DUPLICATE KEY UPDATE ...` statement for adding new tracking row to tracking table is executed for **N** rows instead of 1. Where: 
- **N** is number of rows in table that is tracked,
- Each row have the same values.  Values part uses only `new.{pk_column}` and `utc_timestamp()`.
Resulting in one insert and **N-1** updates.
It causes:
- huge performance issues for first update of not yet tracked table row,
- mysql `Lock wait timeout exceeded` errors when concurrent updates occur.
when provisioned for existing table, that has:
- multiple-column primary key which is not optimized,
- over 500'000 rows.
See [Background](#background) for more detail.
Use `INSERT INTO ... VALUES ...` instead of  `INSERT INTO ... SELECT ...`.
Before: …
=> [Dotmim.Sync.MySql] Optimize update trigger

Projects/Dotmim.Sync.Web.Client/Dotmim.Sync.Web.Client.csproj, Projects/Dotmim.Sync.Web.Client/HttpRequestHandler.cs
Fix Xamarin Form Build in Release mode when add reference to `Microsoft.EntityFrameworkCore.Sqlite >= 5.0.17` and `Dotmim.Sync.Web.Client 0.9.7`
`Microsoft.EntityFrameworkCore.Sqlite` required `Microsoft.Extensions.Primitives (>= 5.0.0)`
`Microsoft.Net.Http.Headers` required `Microsoft.Extensions.Primitives (>= 2.2.0)`
Nuget resolve dependecy using  `Microsoft.Extensions.Primitives 5.0.1` but when build in release mode linker 
throw 
```
Mono.Linker.MarkException: Error processing method: 'System.String Microsoft.Net.Http.Headers.DateTimeFormatter::ToRfc1123String(System.DateTimeOffset,System.Boolean)' in assembly: 'Microsoft.Net.Http.Headers.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Microsoft.Extensions.Primitives.InplaceStringBuilder
```
because …
=> fix: Linker error on Xamarin

Projects/Dotmim.Sync.Core/Setup/SetupFilter.cs
This tripped me up briefly when learning filters,
One AddParameter method of the SetupFilter class uses the arguement 'parameterName' which seems correct where as two others refer to it as 'columnName' which isn't accurate when your column and parameter have different names.
=> Fix inconsistent parameter naming between AddParameter methods

Projects/Dotmim.Sync.MySql/Builders/MySqlScopeInfoBuilder.cs, Projects/Dotmim.Sync.PostgreSql/Builders/NpgsqlScopeBuilder.cs, Projects/Dotmim.Sync.SqlServer/Builders/SqlScopeBuilder.cs
Mixing `sync_scope_id` parameter types can cause issues with syncing. It seems in certain scenarios, GUID parameter converted as a string results in a malformed GUID in the form of `a0a0a0a0a-0001-0000-0000-000000000000` as seen in #962.
GUID values should always be always be converted as `DbType.Guid` consistently.
=> Set sync_scope_id parameter as Guid consistently in Buider classes.

Projects/Dotmim.Sync.Core/Logger/SyncLogger.cs, Projects/Dotmim.Sync.Core/Orchestrators/Commands/BaseOrchestrator.Commands.cs
These changes fix about half of the errors that I detected using InferSharp. The other half involves refactoring the Newtonsoft-based JSON writing code, which seems best left to a separate PR.
These changes seem relatively safe, but please take a look.
Partially Fixes https://github.com/Mimetis/Dotmim.Sync/issues/1005
=> Prevent concurrency issues and clean up non-disposed objects

Projects/Dotmim.Sync.Core/Serialization/LocalJsonSerializer.cs
Unless this is rewritten with System.Text.Json there is a lot of potential thread safety issues.
I have added some more locking to address this.
Fixes the remaining issues flagged here: https://github.com/Mimetis/Dotmim.Sync/issues/1005
=> Add more locking in LocalJsonSerializer

Projects/Dotmim.Sync.Core/Set/SyncColumn.cs, Projects/Dotmim.Sync.Core/Set/SyncColumns.cs, Projects/Dotmim.Sync.PostgreSql/Builders/NpgsqlBuilderTable.cs, Projects/Dotmim.Sync.SqlServer/Builders/SqlBuilderTable.cs, Projects/Dotmim.Sync.SqlServer/SqlSyncAdapter.cs
This is a small performance optimization
see: [CA1854](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1854)
=> use TryGetAdd to avoid double lookups

Projects/Dotmim.Sync.SqlServer/Builders/SqlBuilderTable.cs
Awaiting a task-returning method that returns null can result in a NullReferenceException
https://www.zachsnoek.com/blog/returning-null-from-task-returning-methods-in-c-sharp
=> return Task instead of null

Projects/Dotmim.Sync.Core/EnumerableExtensions.cs, Projects/Dotmim.Sync.Core/Set/SyncNamedItem.cs, Projects/Dotmim.Sync.Core/SyncAgent.cs, Projects/Dotmim.Sync.Core/SyncTypeConverter.cs, Projects/Dotmim.Sync.MariaDB/MariaDBSyncProvider.cs, Projects/Dotmim.Sync.MySql/MySqlSyncProvider.cs, Projects/Dotmim.Sync.PostgreSql/NpgsqlSyncProvider.cs, Projects/Dotmim.Sync.SqlServer/SqlSyncProvider.cs, Projects/Dotmim.Sync.Sqlite/SqliteSyncProvider.cs, Projects/Dotmim.Sync.Web.Server/WebServerAgent.cs
This will reduce casting, because pattern matching already does casting internally. Also makes the code more readable.
I used automatic refactoring via Roslynator to accomplish this.
=> Use pattern matching without casting

Projects/Dotmim.Sync.Core/Logger/SyncLogger.cs, Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.BatchInfo.cs, Projects/Dotmim.Sync.Core/Orchestrators/Provision/RemoteOrchestrator.Provision.cs, Projects/Dotmim.Sync.Core/Orchestrators/Scopes/LocalOrchestrator.ScopeInfos.cs, Projects/Dotmim.Sync.Core/Serialization/LocalJsonSerializer.cs, Projects/Dotmim.Sync.Core/SyncTypeConverter.cs, Projects/Dotmim.Sync.MySql/MySqlTokenizer.cs, Samples/Dotmim.Sync.SampleConsole/DBHelper.cs
May help with performance and also help to enforce correctness. Accomplished with automatic refactoring via [Roslyn Analyzers](https://github.com/dotnet/roslyn-analyzers).
see [CA1822](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1822)
=> Make some methods and classes static

Projects/Dotmim.Sync.Core/Serialization/LocalJsonSerializer.cs
The consensus seems to be that JsonSerializer is thread-safe
https://stackoverflow.com/questions/36186276/is-the-json-net-jsonserializer-threadsafe
=> Newtonsoft JsonSerializer is thread-safe

Projects/Dotmim.Sync.SqlServer/SqlManagementUtils.cs
When using sql change tracking the system table MSChange_tracking_history is created. It should not be included in the list generated by GetAllTablesAsync. It can be excluded by requesting only records from sys.tables where is_ms_shipped=0.
=> Fix for #1025 SqlServer.ChangeTracking MissingPrimaryKeyException: Table MSchange_tracking_history does not have any primary key.

Projects/Dotmim.Sync.MySql/MySqlSyncAdapter.cs, Projects/Dotmim.Sync.PostgreSql/NpgsqlSyncAdapter.cs, Projects/Dotmim.Sync.SqlServer/SqlSyncAdapter.cs
In my opinion we should modify these properties to have only private setters. That initialization should only happen via the constructor, since it seems very likely to break things.
There were no tests for that kind of scenario of changing those properties post-initialization, which is why I was able to cleanly remove the setters.
Removing these setters can simplify the assumptions of all the callers that consume the getters, and allow things like storing a  reference or caching, if we know that they will never be mutated.
Conversely, if using the setters is a supported scenario, then we should add tests around it. And it would be strange to only allow such a thing on some of the adapters, but not all of them, as is currently the case.
=> use private setters for metadata

Projects/Dotmim.Sync.Core/Orchestrators/Upgrade/LocalOrchestrator.Upgrade.cs, Projects/Dotmim.Sync.MySql/Builders/MySqlBuilderTable.cs, Projects/Dotmim.Sync.MySql/Builders/MySqlObjectNames.cs, Projects/Dotmim.Sync.SqlServer/Builders/SqlObjectNames.cs, Projects/Dotmim.Sync.Sqlite/Builders/SQLiteObjectNames.cs, Projects/Dotmim.Sync.Web.Client/Orchestrators/WebRemoteOrchestrator.cs, Projects/Dotmim.Sync.Web.Server/WebServerAgent.cs, Tests/Dotmim.Sync.Tests/HttpTests/HttpTests.cs
This is a continuation of https://github.com/Mimetis/Dotmim.Sync/pull/1015 
Add/Update logic can also avoid ContainsKey() lookups by simply assigning a value for a key via the indexer, as that will either add or update as needed.
=> Avoid double lookups with dictionaries

Projects/Dotmim.Sync.Core/Orchestrators/Upgrade/LocalOrchestrator.Upgrade.cs, Projects/Dotmim.Sync.Core/Serialization/SerializationFactoryCollection.cs, Projects/Dotmim.Sync.Core/SyncAgent.cs, Projects/Dotmim.Sync.MySql/Builders/MySqlBuilderTable.cs, Projects/Dotmim.Sync.MySql/Builders/MySqlDbMetadata.cs, Projects/Dotmim.Sync.MySql/MySqlExtensionsMethods.cs, Projects/Dotmim.Sync.PostgreSql/Builders/NpgsqlDbMetadata.cs, Projects/Dotmim.Sync.SqlServer/Builders/SqlDbMetadata.cs, Projects/Dotmim.Sync.Sqlite/SqliteSyncProvider.cs, Tests/Dotmim.Sync.Tests/Setup.cs
This should be slightly faster and also more explicit. It is the recommended pattern in StyleCop. I used an automated refactoring which ensures that the StringComparison type was unchanged.
see: [CA1307](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1307), [CA1310](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1310)
=> Specify StringComparison directly

Projects/Dotmim.Sync.Core/Serialization/ISerializer.cs, Projects/Dotmim.Sync.Core/Serialization/JsonObjectSerializer.cs
Going along with my other PR https://github.com/Mimetis/Dotmim.Sync/pull/1022 we can safely assume that JsonSerializer is thread-safe, as per the advice of the library author James Newton-King.
A static serializer means we can avoid repeated object creation overhead
JsonSerializer is preferred over JObject because it is faster when we know the type ahead of time. Which we do.
This removes the SerializeAsync(object) overload because the generic version handles that perfectly.
=> use static JsonSerializer

Projects/Dotmim.Sync.Core/Interceptors/SynchronousProgress.cs
See #1141 
If SynchronousProgress is used in a WinUI 3/AppSdk application an exception is thrown when the sync is started which tells:
"The send method is not supported, use Post instead."
Changing line 73 in /Projects/Dotmim.Sync.Core/Interceptors/SynchronousProgress.cs
m_synchronizationContext.Send(m_invokeHandlers, value);
to
m_synchronizationContext.Post(m_invokeHandlers, value);
and everything works fine.
=> #1141 : SynchronousProgress<T> in WinUI 3/AppSdk app

Projects/Dotmim.Sync.Core/Serialization/SerializationFactoryCollection.cs
Nearly everything in here was public, but also completely unused. This might cause confusion.
=> Remove unused functions that were exposed via the API

Projects/Dotmim.Sync.Core/Dotmim.Sync.Core.csproj, Projects/Dotmim.Sync.Core/packages.lock.json, Projects/Dotmim.Sync.MariaDB/packages.lock.json, Projects/Dotmim.Sync.MySql/packages.lock.json, Projects/Dotmim.Sync.PostgreSql/packages.lock.json, Projects/Dotmim.Sync.SqlServer.ChangeTracking/packages.lock.json, Projects/Dotmim.Sync.SqlServer/packages.lock.json, Projects/Dotmim.Sync.Sqlite/packages.lock.json, Projects/Dotmim.Sync.Web.Client/packages.lock.json, Projects/Dotmim.Sync.Web.Server/packages.lock.json, Tests/Dotmim.Sync.Tests/packages.lock.json
Microsoft.Bcl.Build doesn't seem to be necessary for .NET Standard 2.0 and above
This is a one-line change but the lockfiles needed to be regenerated.
=> Remove unused package

Tests/Dotmim.Sync.Tests/Misc/DatabaseTest.cs, Tests/Dotmim.Sync.Tests/TcpTests/TcpFilterTests.cs, Tests/Dotmim.Sync.Tests/TcpTests/TcpTests.ScenarioTests.cs, Tests/Dotmim.Sync.Tests/TcpTests/TcpTests.cs, Tests/Dotmim.Sync.Tests/UnitTests/Interceptors/Interceptors.Tables.Tests.cs, Tests/Dotmim.Sync.Tests/UnitTests/Interceptors/Interceptors.TrackingTables.Tests.cs, Tests/Dotmim.Sync.Tests/UnitTests/Interceptors/Interceptors.Triggers.Tests.cs, Tests/Dotmim.Sync.Tests/UnitTests/Orchestrators/RemoteOrchestrator.StoredProcedures.Tests.cs, Tests/Dotmim.Sync.Tests/UnitTests/Orchestrators/RemoteOrchestrator.Tests.cs, Tests/Dotmim.Sync.Tests/UnitTests/Orchestrators/RemoteOrchestrator.Triggers.Tests.cs, Tests/Dotmim.Sync.Tests/UnitTests/SyncSetup/SyncSetupTests.cs
Avoids array creation by using the `params` syntax that was already existing.
=> use params

Directory.Build.props, Projects/Dotmim.Sync.Core/packages.lock.json, Projects/Dotmim.Sync.MariaDB/packages.lock.json, Projects/Dotmim.Sync.MySql/packages.lock.json, Projects/Dotmim.Sync.PostgreSql/packages.lock.json, Projects/Dotmim.Sync.SqlServer.ChangeTracking/packages.lock.json, Projects/Dotmim.Sync.SqlServer/packages.lock.json, Projects/Dotmim.Sync.Sqlite/packages.lock.json, Projects/Dotmim.Sync.Web.Client/packages.lock.json, Projects/Dotmim.Sync.Web.Server/packages.lock.json, Samples/Dotmim.Sync.SampleConsole/packages.lock.json, Tests/Dotmim.Sync.Tests/packages.lock.json
I turn this on in all my projects. I have never seen any problem. It basically extracts some compiler metadata like timestamps out of the binaries to allow comparison of the binaries.
So running our build scripts on two different computers should produce a binary that is verifiably identical down to the byte. Which is important for both determinism and supply chain integrity. (works well with lockfiles)
I have never seen this introduce any bugs. It doesn't bloat the binaries or cause performance issues. The only maintenance burden is that once in a long while they update the packages.
Fixes #1164 
I linked to more info in that issue.
=> Reproducible builds

Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj, Tests/Dotmim.Sync.Tests/UnitTests/Orchestrators/RemoteOrchestrator.Snapshots.Tests.cs, Tests/Dotmim.Sync.Tests/packages.lock.json
The xUnit analyzers are useful, and having the development nuget package allows them to work in a more cross-platform and cross-IDE manner.
And with it, theoretically, the warnings could be converted into pipeline errors.
=> Add xUnit analyzer, and fix warnings

Samples/Dotmim.Sync.SampleConsole/Dotmim.Sync.SampleConsole.csproj, Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj
There is no synchronization context in a console app, by default
https://stackoverflow.com/questions/25817703/configureawaitfalse-not-needed-in-console-win-service-apps-right
=> don't warn for CA2007 in sample console

Directory.Build.props, Projects/Dotmim.Sync.Core/packages.lock.json, Projects/Dotmim.Sync.MariaDB/packages.lock.json, Projects/Dotmim.Sync.MySql/packages.lock.json, Projects/Dotmim.Sync.PostgreSql/packages.lock.json, Projects/Dotmim.Sync.SqlServer.ChangeTracking/packages.lock.json, Projects/Dotmim.Sync.SqlServer/packages.lock.json, Projects/Dotmim.Sync.Sqlite/packages.lock.json, Projects/Dotmim.Sync.Web.Client/packages.lock.json, Projects/Dotmim.Sync.Web.Server/packages.lock.json, Samples/Dotmim.Sync.SampleConsole/packages.lock.json, Tests/Dotmim.Sync.Tests/Models/AdventureWorksContext.cs, Tests/Dotmim.Sync.Tests/packages.lock.json
This turns on tons of static analysis, and thus adds many thousands of warnings.
To me, it is better to turn them all on, and fix them or silence them explicitly. Rather than not to know about them.
The latest StyleCop beta has the best support for C# 12, which is why I am adding it rather than relying on the built-in version.
`<NoWarn>` can be added at the Directory.Build.props level to apply everywhere for those that you will inevitably want to silence. As long as you use the inheritance pattern I showed in #1209 
Silencing those relating to documentation and naming conventions will probably take care of more than 80% of the warnings, and you can decide which to silence.
=> turn on lots of analyzers

Tests/Dotmim.Sync.Tests/Models/AdventureWorksContext.cs
This is to make the build pipelines green.
=> prevent arithmetic overflow

Projects/Dotmim.Sync.Sqlite/Builders/SQLiteObjectNames.cs, Projects/Dotmim.Sync.Sqlite/Builders/SqliteTableBuilder.cs, Projects/Dotmim.Sync.Sqlite/SQLiteSyncAdapter.cs, Projects/Dotmim.Sync.Sqlite/SqliteSyncProvider.cs, Samples/Dotmim.Sync.SampleConsole/SqliteSyncDownloadOnlyProvider.cs, Tests/Dotmim.Sync.Tests/Setup.cs
Fixes #1215 
Fix SQL Filters Generation Issue in SQLite Provider
This pull request addresses the issue of SQL filters generation in the `SqliteSyncProvider`, as discussed in [Issue #1215](https://github.com/Mimetis/Dotmim.Sync/issues/1215). It introduces a new property `DisableSqlFiltersGeneration` to control whether SQL filters are generated during command creation.
- **New Property**: Introduced `DisableSqlFiltersGeneration` property to `SqliteSyncProvider`.
- **Command Text Generation**: Updated `CreateSelectChangesCommandText` method to conditionally include SQL filters based on the value of `DisableSqlFiltersGeneration`.
- **Tests Added**: Included unit tests to verify the behavior of `DisableSqlFiltersGeneration`.
=> Fixing issue #1215

Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj
when building via command line, these warnings clutter the logs
=> don't warn about documentation in tests

Projects/Dotmim.Sync.Core/Orchestrators/ApplyChanges/BaseOrchestrator.ApplyChanges.cs, Projects/Dotmim.Sync.Core/Orchestrators/Builders/BaseOrchestrator.Table.cs, Projects/Dotmim.Sync.Core/Orchestrators/Metadatas/BaseOrchestrator.Metadatas.cs
This is a redundant LINQ query and list creation operation that is happening all the time.
Threw in another fix for a possible memory leak
=> Only query table list once

Projects/Dotmim.Sync.Core/Orchestrators/ApplyChanges/BaseOrchestrator.ApplyChanges.cs, Projects/Dotmim.Sync.Core/Orchestrators/ApplyChanges/LocalOrchestrator.ApplyChanges.cs, Projects/Dotmim.Sync.Core/Orchestrators/ApplyChanges/RemoteOrchestrator.ApplyChanges.cs, Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.BatchInfo.cs, Projects/Dotmim.Sync.Web.Client/Orchestrators/WebRemoteOrchestrator.GetChanges.cs, Projects/Dotmim.Sync.Web.Server/WebServerAgent.cs, Tests/Dotmim.Sync.Tests/UnitTests/BatchInfos/BatchInfosTests.cs
The `Dispose` and `DisposeAsync` methods already try to close the file because of the `using` statement.
Indeed, the `using` statement is superior, because it will close the file even in the event of an exception, and obviates the need for try-finally logic.
=> remove redundant CloseFile calls

Projects/Dotmim.Sync.Core/Orchestrators/RemoteOrchestrator.Snapshots.cs
This commit adds an IProgress<ProgressArgs> parameter to the CreateSnapshotAsync() methods on the RemoteOrchestrator and passes it to the GetConnectionAsync() method call.
It allows for progress reporting for creating a snapshot as mentioned in #1298
=> Add progress reporting for snapshot creation

Readme.md
This just clutters the Readme. The build status badge links to the same place.
=> Remove redundant link in Readme.md
